# fly.toml file generated for snowy-surf-3384 on 2022-10-05T20:18:01+03:00

app = "snowy-surf-3384"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
  [[services.script_checks]]
    grace_period = "5s"
    command = "~/health_check.sh"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
