name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello-world-job:
    runs-on: ubuntu-20.04
    steps:
      - name: say hello
        run: |
          echo "Hello World!"
      - name: current date
        run: date
      - name: list directory contents
        run: ls -l
        
